import { Archive, CalendarDays, ChevronRight, Clock3, Columns3, FileBarChart, FolderKanban, History, LayoutDashboard, ListTodo, Palette, Plug, SlidersHorizontal, Tags } from 'lucide-react';
import { priorities, statuses } from './boardConfig';
import type { BoardLabel } from './types';

export const menus=[['Dashboard',LayoutDashboard],['Projetos',FolderKanban],['Quadro Kanban',Columns3],['Calendário',CalendarDays],['Tarefas',ListTodo],['Etiquetas',Tags],['Horas registradas',Clock3],['Relatórios',FileBarChart],['Histórico',History],['Arquivados',Archive],['Integrações',Plug]] as const;

type Props={page:string;boardName:string;profileName:string;taskCount:number;labels:BoardLabel[];priority:string;status:string;labelFilter:string;onPage:(value:string)=>void;onCustomize:()=>void;onProfile:()=>void;onPriority:(value:string)=>void;onStatus:(value:string)=>void;onLabel:(value:string)=>void;onClear:()=>void;initials:(value:string)=>string};

export default function AppSidebar(props:Props){
 return <aside><button className="brand" onClick={props.onCustomize} aria-label="Personalizar quadro"><div className="brand-icon"><Columns3 size={21}/></div><span className="brand-copy"><strong>{props.boardName}</strong><small>SEU ESPAÇO DE TRABALHO</small></span><Palette size={15}/></button><button className="workspace" onClick={props.onProfile} aria-label="Editar meu perfil"><span className="avatar">{props.initials(props.profileName)}</span><span className="workspace-name">{props.profileName||'Seu nome'}<small>Editar perfil</small></span><ChevronRight size={15}/></button><p className="nav-label">PRINCIPAL</p><nav>{menus.map(([name,Icon])=><button className={props.page===name?'active':''} key={name} onClick={()=>props.onPage(name)}><Icon size={18}/>{name}{name==='Tarefas'&&<span className="nav-count">{props.taskCount}</span>}</button>)}</nav><div className="quick-filters"><h4><SlidersHorizontal size={15}/> Filtros rápidos</h4><label>Prioridade<select value={props.priority} onChange={e=>props.onPriority(e.target.value)}><option value="">Todas as prioridades</option>{Object.entries(priorities).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></label><label>Status<select value={props.status} onChange={e=>props.onStatus(e.target.value)}><option value="">Todos os status</option>{Object.entries(statuses).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></label><label>Etiqueta<select value={props.labelFilter} onChange={e=>props.onLabel(e.target.value)}><option value="">Todas as etiquetas</option>{props.labels.map(label=><option key={label.id} value={label.id}>{label.name}</option>)}</select></label><button className="text-button clear" onClick={props.onClear}>Limpar filtros</button></div><div className="sidebar-footer"><span className="online-dot"/> Organização que vira resultado.<small>{props.boardName}</small></div></aside>;
}
