import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { Activity, AlertCircle, CheckCircle2, ChevronDown, ChevronRight, Clock3, CloudDownload, CloudUpload, Eye, KeyRound, RefreshCw, RotateCcw, Trash2 } from 'lucide-react';
import { apiRequest } from './api';
import { statuses } from './boardConfig';

type Status={configured:boolean;board_id:number|null;board_name:string;last_sync_at:string|null;mapped_user_id:string;mapped_user_name:string;auto_sync_hours:boolean;pending_hours:number;failed_hours:number;synced_hours:number;pending_statuses:number;imported_board_ids:number[]};
type RemoteBoard={id:number;name:string};
type RemoteUser={id:string;name:string};
type RemoteStage={id:number;name:string;stage_group:string};
type StatusMapping={board_id:number;enabled:boolean;todo_stage_id:number|null;doing_stage_id:number|null;waiting_stage_id:number|null;done_stage_id:number|null};
type UpdateField='title'|'status'|'due_date'|'estimated_hours'|'assignee'|'priority';
type PreviewTask={id:number;title:string;project_id:number|null;project_name:string;status:string;due_date:string;already_imported:boolean;changes:UpdateField[];conflicts:UpdateField[]};
type Preview={tasks:PreviewTask[];total:number;scanned:number;incremental:boolean;completed_hidden:number};
type HourRecord={id:number;task_title:string;remote_task_title:string;remote_task_id:number;hours:number;note:string;created_at:string;runrunit_synced_at:string|null;runrunit_work_period_id:number|null;runrunit_sync_attempted_at:string|null;runrunit_sync_error:string;state:'pending'|'sent'|'failed'};
type IntegrationLog={id:number;operation:string;status:'success'|'error';message:string;created_at:string};
const emptyStatus:Status={configured:false,board_id:null,board_name:'',last_sync_at:null,mapped_user_id:'',mapped_user_name:'',auto_sync_hours:false,pending_hours:0,failed_hours:0,synced_hours:0,pending_statuses:0,imported_board_ids:[]};
const dateLabel=(value:string)=>new Intl.DateTimeFormat('pt-BR').format(new Date(value));
const durationLabel=(hours:number)=>`${Math.floor(hours)}h${Math.round(hours%1*60).toString().padStart(2,'0')}`;

export default function RunrunIntegrationPage({onImported}:{onImported:()=>Promise<void>}){
 const [status,setStatus]=useState<Status>(emptyStatus),[boards,setBoards]=useState<RemoteBoard[]>([]),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[hourRecords,setHourRecords]=useState<HourRecord[]>([]),[hourFilter,setHourFilter]=useState<'all'|'pending'|'sent'|'failed'>('all');
 const [preview,setPreview]=useState<Preview|null>(null),[chosen,setChosen]=useState<Set<number>>(new Set()),[includeCompleted,setIncludeCompleted]=useState(false),[incremental,setIncremental]=useState(false),[expanded,setExpanded]=useState<Set<string>>(new Set());
 const [updateFields,setUpdateFields]=useState<Set<UpdateField>>(new Set(['title','status','due_date','estimated_hours','assignee','priority']));
 const [stages,setStages]=useState<RemoteStage[]>([]),[mapping,setMapping]=useState<StatusMapping|null>(null);
 const [users,setUsers]=useState<RemoteUser[]>([]),[mappedUserId,setMappedUserId]=useState('');
 const [logs,setLogs]=useState<IntegrationLog[]>([]);
 const groups=useMemo(()=>{const grouped=new Map<string,PreviewTask[]>();for(const task of preview?.tasks||[]){const key=task.project_name||'Sem projeto';grouped.set(key,[...(grouped.get(key)||[]),task])}return [...grouped.entries()]},[preview]);
 const visibleHours=hourRecords.filter(row=>hourFilter==='all'||row.state===hourFilter);
 async function load(loadBoards=true){const next=await apiRequest('/integrations/runrunit') as Status;setStatus(next);setMappedUserId(next.mapped_user_id||'');if(next.configured){const [hours,history]=await Promise.all([apiRequest('/integrations/runrunit/hours'),apiRequest('/integrations/runrunit/history')]) as [HourRecord[],IntegrationLog[]];setHourRecords(hours);setLogs(history);if(loadBoards){const [rows,remoteUsers]=await Promise.all([apiRequest('/integrations/runrunit/boards'),apiRequest('/integrations/runrunit/users')]) as [RemoteBoard[],RemoteUser[]];setBoards(rows);setUsers(remoteUsers);setSelected(String(next.board_id||rows[0]?.id||''))}}}
 useEffect(()=>{void load().catch(e=>setError((e as Error).message))},[]);
 useEffect(()=>{if(!status.configured||!selected){setStages([]);setMapping(null);return}void Promise.all([apiRequest(`/integrations/runrunit/boards/${selected}/stages`),apiRequest(`/integrations/runrunit/boards/${selected}/status-mapping`)]).then(([remoteStages,saved])=>{setStages(remoteStages as RemoteStage[]);setMapping(saved as StatusMapping)}).catch(e=>setError((e as Error).message))},[selected,status.configured]);
 async function connect(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');setMessage('');const form=new FormData(event.currentTarget);try{await apiRequest('/integrations/runrunit','PUT',{app_key:String(form.get('app_key')||'').trim(),user_token:String(form.get('user_token')||'').trim()});await load();setMessage('Conexão realizada. Agora escolha o quadro que deseja importar.');event.currentTarget.reset()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function preparePreview(){if(!selected)return;setBusy(true);setError('');setMessage('');try{const result=await apiRequest('/integrations/runrunit/preview','POST',{board_id:Number(selected),include_completed:includeCompleted,incremental}) as Preview;setPreview(result);setChosen(new Set(result.tasks.map(task=>task.id)));setExpanded(new Set(result.tasks.map(task=>task.project_name||'Sem projeto')))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function toggleTask(id:number){setChosen(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next})}
 function toggleProject(tasks:PreviewTask[]){setChosen(current=>{const next=new Set(current);const all=tasks.every(task=>next.has(task.id));for(const task of tasks)all?next.delete(task.id):next.add(task.id);return next})}
 function toggleUpdateField(field:UpdateField){setUpdateFields(current=>{const next=new Set(current);next.has(field)?next.delete(field):next.add(field);return next})}
 async function importBoard(){const board=boards.find(item=>item.id===Number(selected));if(!board||!preview||!chosen.size)return;setBusy(true);setError('');setMessage('');try{const result=await apiRequest('/integrations/runrunit/import','POST',{board_id:board.id,board_name:board.name,task_ids:[...chosen],update_fields:[...updateFields]});await onImported();await load(false);setMessage(`${result.tasks_created} tarefas adicionadas e ${result.tasks_updated} atualizadas.${result.backup_created?' Uma cópia de segurança foi criada antes da importação.':''}`);setPreview(null)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function syncHours(){setBusy(true);setError('');setMessage('');try{const result=await apiRequest('/integrations/runrunit/sync-hours','POST');await load(false);if(result.errors?.length)setError(`${result.sent} registros enviados; ${result.errors.length} não puderam ser enviados.`);else setMessage(`${result.sent} registros de horas enviados ao Runrun.it.`)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function retryHours(){setBusy(true);setError('');setMessage('');try{const result=await apiRequest('/integrations/runrunit/retry-hours','POST');await load(false);if(result.errors?.length)setError(`${result.sent} registros enviados; ${result.errors.length} ainda apresentam erro.`);else setMessage(`${result.sent} registros com falha foram enviados ao Runrun.it.`)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function saveMapping(){if(!mapping)return;setBusy(true);setError('');setMessage('');try{await apiRequest(`/integrations/runrunit/boards/${mapping.board_id}/status-mapping`,'PUT',mapping);setMessage(mapping.enabled?'Sincronização automática de status ativada.':'Mapeamento salvo com a sincronização automática desativada.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function syncStatuses(){setBusy(true);setError('');setMessage('');try{const result=await apiRequest('/integrations/runrunit/sync-statuses','POST');await load(false);if(result.failed)setError(`${result.sent} status enviados; ${result.failed} apresentaram erro.`);else setMessage(`${result.sent} status de tarefas enviados ao Runrun.it.`)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function saveUserMapping(){const user=users.find(item=>item.id===mappedUserId);setBusy(true);setError('');setMessage('');try{await apiRequest('/integrations/runrunit/user-mapping','PUT',{user_id:mappedUserId,user_name:user?.name||''});await load(false);setMessage(mappedUserId?'Usuário do Runrun.it vinculado ao perfil local.':'Vínculo de usuário removido.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function setAutoSyncHours(enabled:boolean){setBusy(true);setError('');try{await apiRequest('/integrations/runrunit/automation','PUT',{auto_sync_hours:enabled});setStatus(current=>({...current,auto_sync_hours:enabled}));setMessage(enabled?'Envio automático de horas ativado.':'Envio automático de horas desativado.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function removeImport(){const board=boards.find(item=>item.id===Number(selected));if(!board||!confirm(`Remover as tarefas e projetos importados de “${board.name}”? Os registros de horas serão preservados.`))return;setBusy(true);setError('');setMessage('');try{const result=await apiRequest(`/integrations/runrunit/import/${board.id}`,'DELETE');await onImported();await load(false);setPreview(null);setMessage(`${result.tasks_removed} tarefas e ${result.projects_removed} projetos importados foram removidos.`)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="integration-grid">
  <section className="panel integration-card"><div className="integration-title"><span><KeyRound size={20}/></span><div><h3>Conexão com o Runrun.it</h3><p>Use as credenciais de API da sua conta. Elas ficam protegidas neste computador.</p></div>{status.configured&&<b><CheckCircle2 size={14}/> Conectado</b>}</div><form onSubmit={connect}><label>App-Key<input name="app_key" type="password" autoComplete="off" required placeholder="Cole a App-Key"/></label><label>User-Token<input name="user_token" type="password" autoComplete="off" required placeholder="Cole o User-Token"/></label><button className="primary" disabled={busy}>{busy?'Verificando…':status.configured?'Atualizar conexão':'Conectar'}</button></form>{status.configured&&<div className="user-mapping"><label>Usuário correspondente no Runrun.it<select value={mappedUserId} onChange={event=>setMappedUserId(event.target.value)}><option value="">Sem vínculo</option>{users.map(user=><option key={user.id} value={user.id}>{user.name}</option>)}</select></label><button onClick={()=>void saveUserMapping()} disabled={busy}>Salvar usuário</button><small>Os registros de horas continuam sendo enviados pela conta das credenciais conectadas.</small></div>}</section>
  {status.configured&&<section className="panel integration-card import-card"><div className="integration-title"><span><CloudDownload size={20}/></span><div><h3>Importar um quadro</h3><p>Revise os projetos e tarefas antes de confirmar a importação.{status.last_sync_at&&<> Última sincronização: {new Date(status.last_sync_at).toLocaleString('pt-BR')}.</>}</p></div></div><label>Quadro do Runrun.it<select value={selected} onChange={event=>{setSelected(event.target.value);setPreview(null)}}><option value="">Selecione um quadro</option>{boards.map(board=><option key={board.id} value={board.id}>{board.name}</option>)}</select></label><div className="integration-options"><label className="integration-check"><input type="checkbox" checked={includeCompleted} onChange={event=>{setIncludeCompleted(event.target.checked);setPreview(null)}}/><span>Incluir tarefas concluídas</span></label><label className="integration-check"><input type="checkbox" checked={incremental} onChange={event=>{setIncremental(event.target.checked);setPreview(null)}}/><span>Mostrar somente tarefas novas ou alteradas</span></label></div><div className="integration-actions"><button onClick={()=>void load()} disabled={busy}><RefreshCw size={15}/> Atualizar quadros</button><button onClick={()=>void preparePreview()} disabled={busy||!selected}><Eye size={15}/> Preparar importação</button></div>
  {preview&&<div className="import-preview"><div className="preview-heading"><div><strong>Prévia da importação</strong><small>{preview.total} disponíveis{preview.incremental?` entre ${preview.scanned} verificadas`:''}{preview.completed_hidden?` · ${preview.completed_hidden} concluídas ocultadas`:''}</small></div><span>{chosen.size} selecionadas</span></div><fieldset className="update-field-picker"><legend>Campos que podem ser atualizados nas tarefas já existentes</legend>{([['title','Título'],['status','Status'],['due_date','Prazo'],['estimated_hours','Estimativa'],['assignee','Responsável'],['priority','Prioridade']] as [UpdateField,string][]).map(([field,label])=><label key={field}><input type="checkbox" checked={updateFields.has(field)} onChange={()=>toggleUpdateField(field)}/>{label}</label>)}</fieldset><div className="preview-projects">{groups.map(([name,tasks])=>{const open=expanded.has(name),all=tasks.every(task=>chosen.has(task.id)),some=tasks.some(task=>chosen.has(task.id));return <section className="preview-project" key={name}><div className="preview-project-heading"><button className="icon-button" onClick={()=>setExpanded(current=>{const next=new Set(current);next.has(name)?next.delete(name):next.add(name);return next})}>{open?<ChevronDown size={14}/>:<ChevronRight size={14}/>}</button><input type="checkbox" checked={all} ref={input=>{if(input)input.indeterminate=!all&&some}} onChange={()=>toggleProject(tasks)} aria-label={'Selecionar projeto '+name}/><button className="preview-project-name" onClick={()=>setExpanded(current=>{const next=new Set(current);next.has(name)?next.delete(name):next.add(name);return next})}><strong>{name}</strong><small>{tasks.length} tarefas</small></button></div>{open&&<div className="preview-tasks">{tasks.map(task=><label key={task.id}><input type="checkbox" checked={chosen.has(task.id)} onChange={()=>toggleTask(task.id)}/><span><strong>{task.title}{task.already_imported&&<em>Já importada</em>}</strong><small>{statuses[task.status]}{task.due_date?` · Prazo ${task.due_date.split('-').reverse().join('/')}`:''}</small>{task.already_imported&&<small>{task.changes.length?`Alterações: ${task.changes.map(field=>({title:'título',status:'status',due_date:'prazo',estimated_hours:'estimativa',assignee:'responsável',priority:'prioridade'}[field])).join(', ')}`:'Sem alterações no Runrun.it'}</small>}{task.conflicts.length>0&&<small className="conflict-warning">Conflito local e remoto: {task.conflicts.map(field=>({title:'título',status:'status',due_date:'prazo',estimated_hours:'estimativa',assignee:'responsável',priority:'prioridade'}[field])).join(', ')}</small>}</span></label>)}</div>}</section>})}</div><div className="preview-actions"><button onClick={()=>setChosen(new Set())}>Limpar seleção</button><button className="primary" onClick={()=>void importBoard()} disabled={busy||!chosen.size}><CloudDownload size={15}/> Importar {chosen.size} tarefas</button></div></div>}
  {mapping&&stages.length>0&&<section className="status-mapping"><div><strong>Sincronização de status</strong><small>Relacione cada coluna local a uma etapa deste quadro.</small></div><label className="integration-check"><input type="checkbox" checked={mapping.enabled} onChange={event=>setMapping({...mapping,enabled:event.target.checked})}/><span>Atualizar automaticamente ao mover uma tarefa</span></label><div className="status-mapping-grid">{(['todo','doing','waiting','done'] as const).map(key=><label key={key}>{statuses[key]}<select value={mapping[`${key}_stage_id`]||''} onChange={event=>setMapping({...mapping,[`${key}_stage_id`]:event.target.value?Number(event.target.value):null})}><option value="">Selecione</option>{stages.map(stage=><option key={stage.id} value={stage.id}>{stage.name}{stage.stage_group==='closed'?' · concluída':''}</option>)}</select></label>)}</div><div className="integration-actions"><button onClick={()=>void saveMapping()} disabled={busy}>Salvar mapeamento</button><button className="primary" onClick={()=>void syncStatuses()} disabled={busy||status.pending_statuses===0||!mapping.enabled}><RefreshCw size={15}/> Enviar {status.pending_statuses} status pendentes</button></div></section>}
  <div className="integration-actions"><button className="danger" onClick={()=>void removeImport()} disabled={busy||!selected||!status.imported_board_ids.includes(Number(selected))}><Trash2 size={15}/> Remover importação</button></div></section>}
  {status.configured&&<section className="panel integration-card hours-sync-card"><div className="integration-title"><span><CloudUpload size={20}/></span><div><h3>Registros de horas</h3><p>Acompanhe cada envio realizado para as tarefas vinculadas.</p></div></div><label className="integration-check auto-sync-option"><input type="checkbox" checked={status.auto_sync_hours} disabled={busy} onChange={event=>void setAutoSyncHours(event.target.checked)}/><span>Enviar automaticamente ao finalizar um cronômetro</span></label><div className="hour-summary"><button className={hourFilter==='pending'?'active':''} onClick={()=>setHourFilter('pending')}><Clock3 size={14}/><strong>{status.pending_hours}</strong><span>Pendentes</span></button><button className={hourFilter==='failed'?'active':''} onClick={()=>setHourFilter('failed')}><AlertCircle size={14}/><strong>{status.failed_hours}</strong><span>Com erro</span></button><button className={hourFilter==='sent'?'active':''} onClick={()=>setHourFilter('sent')}><CheckCircle2 size={14}/><strong>{status.synced_hours}</strong><span>Enviados</span></button><button className={hourFilter==='all'?'active':''} onClick={()=>setHourFilter('all')}><strong>{hourRecords.length}</strong><span>Todos</span></button></div><div className="hour-record-list">{visibleHours.length?visibleHours.map(row=><article className={`hour-record ${row.state}`} key={row.id}><span className="hour-state">{row.state==='sent'?<CheckCircle2 size={15}/>:row.state==='failed'?<AlertCircle size={15}/>:<Clock3 size={15}/>}</span><div><strong>{row.task_title}</strong><small>Runrun.it #{row.remote_task_id} · {row.remote_task_title}</small>{row.note&&<small>{row.note}</small>}{row.runrunit_sync_error&&<small className="hour-error">{row.runrunit_sync_error}</small>}</div><div className="hour-record-meta"><strong>{durationLabel(row.hours)}</strong><span>{dateLabel(row.created_at)}</span>{row.runrunit_work_period_id&&<small>Envio #{row.runrunit_work_period_id}</small>}</div></article>):<p className="empty-hour-records">Nenhum registro nesta situação.</p>}</div><div className="integration-actions"><button onClick={()=>void retryHours()} disabled={busy||status.failed_hours===0}><RotateCcw size={15}/> Tentar erros novamente</button><button className="primary" onClick={()=>void syncHours()} disabled={busy||status.pending_hours===0}><CloudUpload size={15}/> Enviar pendentes</button></div></section>}
  {status.configured&&<section className="panel integration-card integration-history"><div className="integration-title"><span><Activity size={20}/></span><div><h3>Histórico da integração</h3><p>Últimas importações e sincronizações realizadas.</p></div></div><div>{logs.length?logs.map(log=><article className={log.status} key={log.id}>{log.status==='success'?<CheckCircle2 size={14}/>:<AlertCircle size={14}/>}<span><strong>{({import:'Importação',hours:'Horas',status:'Status'} as Record<string,string>)[log.operation]||log.operation}</strong><small>{log.message}</small></span><time>{new Date(log.created_at).toLocaleString('pt-BR')}</time></article>):<p className="empty-hour-records">Nenhuma operação registrada ainda.</p>}</div></section>}
  {message&&<div className="integration-message" role="status"><CheckCircle2 size={17}/>{message}</div>}{error&&<div className="error" role="alert">{error}</div>}
 </div>;
}
