import { useEffect, useState } from 'react';
import { CheckCircle2, CloudUpload, Link2, Link2Off, RefreshCw, Search, X } from 'lucide-react';
import { apiRequest } from './api';
import type { Entry, Task } from './types';
import TaskEditorSection from './TaskEditorSection';

type Board={id:number;name:string};
type RemoteTask={id:number;title:string;project_name:string;already_imported:boolean;linked_count:number};
type Status={configured:boolean};

export default function RunrunTaskLink({task,entries,onChanged}:{task:Task;entries:Entry[];onChanged:()=>Promise<void>}){
 const [configured,setConfigured]=useState(false),[editing,setEditing]=useState(!task.runrunit_id),[boards,setBoards]=useState<Board[]>([]),[boardId,setBoardId]=useState(String(task.runrunit_board_id||'')),[taskQuery,setTaskQuery]=useState(''),[remoteTasks,setRemoteTasks]=useState<RemoteTask[]>([]),[remoteId,setRemoteId]=useState(String(task.runrunit_id||'')),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const pending=entries.filter(entry=>entry.task_id===task.id&&!entry.runrunit_synced_at).length;
 const filteredTasks=remoteTasks.filter(item=>!taskQuery.trim()||`${item.project_name} ${item.title}`.toLocaleLowerCase('pt-BR').includes(taskQuery.trim().toLocaleLowerCase('pt-BR')));
 useEffect(()=>{void Promise.all([apiRequest('/integrations/runrunit'),apiRequest('/integrations/runrunit/boards')]).then(([status,items])=>{setConfigured((status as Status).configured);setBoards(items as Board[])}).catch(()=>setConfigured(false))},[]);
 async function loadTasks(){if(!boardId)return;setBusy(true);setError('');setTaskQuery('');try{const result=await apiRequest('/integrations/runrunit/preview','POST',{board_id:Number(boardId),include_completed:true});setRemoteTasks(result.tasks);if(!remoteId)setRemoteId(String(result.tasks[0]?.id||''))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function link(){const board=boards.find(item=>item.id===Number(boardId));if(!board||!remoteId)return;setBusy(true);setError('');try{await apiRequest('/integrations/runrunit/link','POST',{task_id:task.id,board_id:board.id,board_name:board.name,runrunit_task_id:Number(remoteId)});await onChanged()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function unlink(){if(!confirm('Desvincular esta tarefa do Runrun.it? As tarefas e horas locais serão preservadas.'))return;setBusy(true);setError('');try{await apiRequest(`/integrations/runrunit/link/${task.id}`,'DELETE');await onChanged()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function sync(){setBusy(true);setError('');setMessage('');try{const result=await apiRequest(`/integrations/runrunit/tasks/${task.id}/sync-hours`,'POST');setMessage(`${result.sent} registros enviados ao Runrun.it.`);await onChanged()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(!configured)return <TaskEditorSection title="Runrun.it" description="Integração não configurada" icon={<Link2 size={15}/>}><p className="subtle">Configure a integração na página Integrações para vincular esta tarefa.</p></TaskEditorSection>;
 return <TaskEditorSection title="Runrun.it" description={task.runrunit_id?(task.runrunit_task_title||`Tarefa ${task.runrunit_id}`):'Vincule esta tarefa a um item remoto'} count={task.runrunit_id?'Vinculada':undefined} icon={<Link2 size={15}/>}>
  <section className="runrun-task-link"><div className="runrun-link-heading"><Link2 size={15}/><div><strong>Sincronização de horas</strong><small>{task.runrunit_id?'Tarefa vinculada e pronta para sincronizar horas.':'Escolha o quadro e a tarefa que receberão as horas.'}</small></div>{task.runrunit_id&&<span><CheckCircle2 size={13}/> Vinculada</span>}</div>
  {task.runrunit_id&&!editing?<div className="runrun-link-current"><div><strong>{task.runrunit_task_title||`Tarefa ${task.runrunit_id}`}</strong><small>{task.runrunit_board_name||`Quadro ${task.runrunit_board_id}`} · ID {task.runrunit_id}</small></div><div><button type="button" onClick={()=>setEditing(true)}>Alterar vínculo</button><button type="button" className="danger" onClick={()=>void unlink()} disabled={busy}><Link2Off size={14}/> Desvincular</button></div></div>:<div className="runrun-link-form"><label>Quadro<select value={boardId} onChange={event=>{setBoardId(event.target.value);setTaskQuery('');setRemoteTasks([]);setRemoteId('')}}><option value="">Selecione</option>{boards.map(board=><option key={board.id} value={board.id}>{board.name}</option>)}</select></label><button type="button" onClick={()=>void loadTasks()} disabled={busy||!boardId}><RefreshCw size={14}/> Carregar tarefas</button>{remoteTasks.length>0&&<><label className="runrun-task-filter">Buscar tarefa<span><Search size={14}/><input value={taskQuery} onChange={event=>setTaskQuery(event.target.value)} placeholder="Digite o nome da tarefa ou projeto"/>{taskQuery&&<button type="button" className="icon-button" onClick={()=>setTaskQuery('')} aria-label="Limpar busca"><X size={13}/></button>}</span><small>{filteredTasks.length} de {remoteTasks.length} tarefas</small></label><label>Tarefa do Runrun.it<select value={remoteId} onChange={event=>setRemoteId(event.target.value)}><option value="">Selecione</option>{filteredTasks.map(item=><option key={item.id} value={item.id}>{item.project_name} — {item.title}{item.linked_count?(item.linked_count===1?' (1 vínculo local)':` (${item.linked_count} vínculos locais)`):''}</option>)}</select></label></>}<div className="runrun-link-actions">{task.runrunit_id&&<button type="button" onClick={()=>setEditing(false)}>Cancelar</button>}<button type="button" className="primary" onClick={()=>void link()} disabled={busy||!remoteId}><Link2 size={14}/> Confirmar vínculo</button></div></div>}
  {task.runrunit_id&&<div className="runrun-pending"><span>{pending} registro{pending===1?'':'s'} de horas pendente{pending===1?'':'s'}</span><button type="button" className="primary" disabled={busy||!pending} onClick={()=>void sync()}><CloudUpload size={14}/> Enviar horas desta tarefa</button></div>}{message&&<p className="success-text">{message}</p>}{error&&<p className="error">{error}</p>}
  </section>
 </TaskEditorSection>;
}
